services:
  api:
    build: .
    container_name: landbot_api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=TEST
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/api
    depends_on:
      - redis


  redis:
    image: redis:alpine
    container_name: landbot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  celery_worker:
    build: .
    container_name: landbot_celery_worker
    command: celery -A landbot worker --loglevel=info
    environment:
      - ENVIRONMENT=TEST
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/api
    depends_on:
      - redis
      - api

volumes:
  redis_data:
