name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install poetry
          poetry install --no-root

      - name: Format code with Black
        run: |
          poetry run black .

      - name: Lint with flake8
        run: |
          poetry run flake8 . --show-source --max-complexity=10 --max-line-length=128 --statistics

      - name: Test with pytest
        run: |
          poetry run pytest -vvv
